const cryptogs = require("./cryptogs.js")
cryptogs.mint(0,"genesiscryptog.png",1)
cryptogs.mint(0,"ethereumlogo.png",1)
cryptogs.mint(0,"ethereumlogo.png",1)
cryptogs.mint(0,"ethereumlogo.png",1)
cryptogs.mint(0,"ethereumlogo.png",1)
cryptogs.mint(0,"ethereumlogo.png",2)
cryptogs.mint(0,"ethereumlogo.png",2)
cryptogs.mint(0,"ethereumlogo.png",2)
cryptogs.mint(0,"ethereumlogo.png",2)
cryptogs.mint(0,"ethereumlogo.png",2)
